In [1]:
# 모든 df의 행이 같을 때 사용 가능.
# ppt 테이블 screenshot 필요

- tab : 자동완성
- shift + tab : 도움말

In [2]:
import pandas as pd

In [6]:
df1 = pd.read_csv("2016_health_checkup_1.csv")

In [8]:
df1.columns

Index(['가입자일련번호', '성별코드', '연령대코드(5세단위)', '시도코드', '신장(5Cm단위)', '체중(5Kg단위)',
       '허리둘레', '시력(좌)', '시력(우)', '청력(좌)', '청력(우)', '수축기혈압', '이완기혈압',
       '식전혈당(공복혈당)', '총콜레스테롤', '트리글리세라이드', 'HDL콜레스테롤', 'LDL콜레스테롤', '혈색소',
       '요단백', '혈청크레아티닌', '(혈청지오티)AST', '(혈청지오티)ALT', '감마지티피', '흡연상태',
       '구강검진 수검여부', '치석', '당뇨병 의사 판정', '고혈압 의사 판정', '간기능 이상여부', '알콜성간염여부'],
      dtype='object')

In [9]:
df2 = pd.read_csv("2016_health_checkup_2.csv")

In [10]:
df2.columns

Index(['가입자일련번호', '성별코드', '연령대코드(5세단위)', '시도코드', '신장(5Cm단위)', '체중(5Kg단위)',
       '허리둘레', '시력(좌)', '시력(우)', '청력(좌)', '청력(우)', '수축기혈압', '이완기혈압',
       '식전혈당(공복혈당)', '총콜레스테롤', '트리글리세라이드', 'HDL콜레스테롤', 'LDL콜레스테롤', '혈색소',
       '요단백', '혈청크레아티닌', '(혈청지오티)AST', '(혈청지오티)ALT', '감마지티피', '흡연상태',
       '구강검진 수검여부', '치석', '당뇨병 의사 판정', '고혈압 의사 판정', '간기능 이상여부', '알콜성간염여부'],
      dtype='object')

In [13]:
df1.columns.equals(df2.columns)

True

In [16]:
print(df1.shape)
print(df2.shape)

(250000, 31)
(250000, 31)

### 2개 병합

In [23]:
# 500000 rows × 31 columns
# 새로운 변수로 선언하면 병합 df를 들고다닐 수 있다.
pd.concat([df1, df2])

,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),...,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진 수검여부,치석,당뇨병 의사 판정,고혈압 의사 판정,간기능 이상여부,알콜성간염여부
0,604509,1,12,41,165.0,65.0,7.0,1.2,1.0,1.0,...,21.0,17.0,17.0,1.0,0,NaN,0.0,0.0,0.0,0.0
1,360197,2,17,43,130.0,25.0,50.0,0.3,0.9,1.0,...,18.0,7.0,19.0,1.0,0,NaN,0.0,0.0,0.0,1.0
2,201061,2,17,45,150.0,135.0,51.0,0.5,0.5,1.0,...,21.0,18.0,24.0,1.0,0,NaN,1.0,0.0,0.0,0.0
3,586237,2,12,41,145.0,35.0,51.0,1.5,0.7,1.0,...,15.0,14.0,18.0,3.0,0,NaN,0.0,0.0,0.0,0.0
4,922457,2,9,11,150.0,35.0,51.0,1.2,1.0,1.0,...,18.0,10.0,20.0,1.0,1,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,920694,1,14,45,NaN,NaN,90.0,1.5,9.9,2.0,...,27.0,19.0,35.0,1.0,0,NaN,0.0,1.0,0.0,0.0
249996,933726,1,11,45,NaN,NaN,86.0,0.9,0.8,1.0,...,19.0,15.0,66.0,1.0,0,NaN,0.0,0.0,0.0,0.0
249997,950762,2,10,45,NaN,NaN,83.0,1.0,1.0,1.0,...,15.0,18.0,27.0,1.0,0,NaN,1.0,0.0,0.0,0.0
249998,969362,1,8,41,NaN,NaN,90.0,1.2,1.2,1.0,...,20.0,20.0,20.0,2.0,0,NaN,0.0,0.0,0.0,0.0
249999,992166,1,9,11,NaN,NaN,NaN,NaN,NaN,NaN,...,23.0,35.0,57.0,2.0,0,NaN,0.0,0.0,0.0,0.0

### 3개 병합

In [18]:
df3 = pd.read_csv("2016_health_checkup_3.csv")

In [20]:
df1.columns.intersection(df2.columns).equals(df3.columns)

True

In [21]:
pd.concat([df1, df2, df3])

,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),...,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진 수검여부,치석,당뇨병 의사 판정,고혈압 의사 판정,간기능 이상여부,알콜성간염여부
0,604509,1,12,41,165.0,65.0,7.0,1.2,1.0,1.0,...,21.0,17.0,17.0,1.0,0,NaN,0.0,0.0,0.0,0.0
1,360197,2,17,43,130.0,25.0,50.0,0.3,0.9,1.0,...,18.0,7.0,19.0,1.0,0,NaN,0.0,0.0,0.0,1.0
2,201061,2,17,45,150.0,135.0,51.0,0.5,0.5,1.0,...,21.0,18.0,24.0,1.0,0,NaN,1.0,0.0,0.0,0.0
3,586237,2,12,41,145.0,35.0,51.0,1.5,0.7,1.0,...,15.0,14.0,18.0,3.0,0,NaN,0.0,0.0,0.0,0.0
4,922457,2,9,11,150.0,35.0,51.0,1.2,1.0,1.0,...,18.0,10.0,20.0,1.0,1,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,921014,1,8,28,NaN,NaN,82.0,0.9,1.2,1.0,...,22.0,29.0,44.0,3.0,0,NaN,0.0,0.0,0.0,0.0
249996,936418,2,9,45,NaN,NaN,69.0,1.5,1.5,1.0,...,17.0,11.0,24.0,1.0,0,NaN,0.0,0.0,0.0,0.0
249997,952842,1,12,26,NaN,NaN,81.0,1.5,0.9,2.0,...,15.0,16.0,42.0,1.0,1,0.0,0.0,0.0,0.0,0.0
249998,971446,2,16,27,NaN,NaN,80.0,NaN,NaN,2.0,...,60.0,52.0,60.0,1.0,1,0.0,0.0,0.0,1.0,0.0
249999,995666,2,11,45,NaN,NaN,79.0,0.6,0.7,1.0,...,20.0,15.0,18.0,1.0,0,NaN,0.0,0.0,0.0,0.0

### 여러 개 병합

In [24]:
# 파일명이 비슷하다. 따라서:
for i in ['1', '2', '3', '4']:
    print("2016_health_checkup_"+ i +".csv")

2016_health_checkup_1.csv
2016_health_checkup_2.csv
2016_health_checkup_3.csv
2016_health_checkup_4.csv

In [25]:
df_raw = pd.DataFrame()
for i in ['1', '2', '3', '4']:
    df_ = pd.read_csv("2016_health_checkup_"+ i +".csv")
    df_raw = pd.concat([df_raw, df_])

# loop 이해
# empty, 1
# empty1, 2
# empty12, 3
# empty123, 4